import type {
  Workspace,
  Project,
  Contractor,
  Task,
  ScopeItem,
  Contact,
  Lead,
  DoorVisit,
} from "./types";
function day(offset: number) {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}
export function demoWorkspace(): Workspace {
  const base = {
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  const contractors: Contractor[] = [
    {
      ...base,
      id: "c1",
      name: "James Wilson",
      company: "Wilson General Contracting",
      trade: "General contractor",
      email: "james@example.com",
      phone: "(919) 555-0101",
      notes: "Sample contractor. Replace with your actual team.",
    },
    {
      ...base,
      id: "c2",
      name: "Mike Davis",
      company: "Davis Flooring Co.",
      trade: "Flooring",
      email: "mike@example.com",
      phone: "(919) 555-0102",
      notes: "LVP, hardwood, and tile installation.",
    },
    {
      ...base,
      id: "c3",
      name: "Sarah Chen",
      company: "Carolina Stoneworks",
      trade: "Countertops",
      email: "sarah@example.com",
      phone: "(919) 555-0103",
      notes: "Countertop templating and installation.",
    },
    {
      ...base,
      id: "c4",
      name: "David Brooks",
      company: "Brooks Electrical",
      trade: "Electrical",
      email: "david@example.com",
      phone: "(919) 555-0104",
      notes: "Licensed electrician. Sample contact.",
    },
    {
      ...base,
      id: "c5",
      name: "Luis Martinez",
      company: "Martinez Tile & Bath",
      trade: "Tile & plumbing",
      email: "luis@example.com",
      phone: "(919) 555-0105",
      notes: "Bathroom tile and fixture installation.",
    },
  ];
  const projects: Project[] = [
    {
      ...base,
      id: "p1",
      name: "Oakwood kitchen remodel",
      client: "The Miller family",
      address: "214 Oakwood Avenue, Raleigh, NC",
      contractPrice: 48500,
      startDate: day(-21),
      endDate: day(18),
      status: "In progress",
      description:
        "Complete kitchen renovation including new shaker cabinetry, quartz countertops, LVP flooring, updated lighting, and a tile backsplash. Retain the existing layout and refresh all finishes.\n\nProtect adjacent living areas throughout construction. Coordinate appliance delivery before countertop installation.",
      category: "Kitchen",
      cover: "/images/kitchen.jpg",
    },
    {
      ...base,
      id: "p2",
      name: "Cary primary bathroom",
      client: "The Henderson family",
      address: "807 Meadow Lane, Cary, NC",
      contractPrice: 32750,
      startDate: day(-14),
      endDate: day(12),
      status: "In progress",
      description:
        "Transform the primary bathroom with a walk-in shower, freestanding tub, double vanity, and new tile throughout.",
      category: "Bathroom",
      cover: "/images/bathroom.jpg",
    },
    {
      ...base,
      id: "p3",
      name: "Apex basement finish",
      client: "The Thompson family",
      address: "156 Maple Ridge Drive, Apex, NC",
      contractPrice: 64200,
      startDate: day(-7),
      endDate: day(42),
      status: "In progress",
      description:
        "Finish the lower level to create a family room, home office, and full bathroom. Includes framing, electrical, insulation, drywall, and flooring.",
      category: "Basement",
      cover: "/images/basement.jpg",
    },
    {
      ...base,
      id: "p4",
      name: "Holly Springs outdoor living",
      client: "The Parker family",
      address: "422 Sunset Way, Holly Springs, NC",
      contractPrice: 28900,
      startDate: day(7),
      endDate: day(40),
      status: "Planning",
      description:
        "Build a covered outdoor living area with composite decking, recessed lighting, and a ceiling fan.",
      category: "Outdoor",
      cover: "/images/outdoor.jpg",
    },
    {
      ...base,
      id: "p5",
      name: "Wake Forest living space",
      client: "The Bennett family",
      address: "63 Heritage Oaks, Wake Forest, NC",
      contractPrice: 41300,
      startDate: day(-5),
      endDate: day(30),
      status: "On hold",
      description:
        "Refresh the main living space with new flooring, a fireplace surround, built-in shelving, and fresh paint. Awaiting final material selections.",
      category: "Whole home",
      cover: "/images/home.jpg",
    },
    {
      ...base,
      id: "p6",
      name: "North Hills guest bathroom",
      client: "The Robinson family",
      address: "910 Glenwood Court, Raleigh, NC",
      contractPrice: 18600,
      startDate: day(-48),
      endDate: day(-4),
      completedDate: day(-4),
      status: "Completed",
      description:
        "Guest bathroom renovation with a new vanity, shower enclosure, tile, and lighting. Final walkthrough complete.",
      category: "Bathroom",
      cover: "/images/bathroom.jpg",
    },
  ];
  const taskRows: [
    string,
    string,
    string,
    number,
    Task["priority"],
    Task["status"],
  ][] = [
    ["p1", "Confirm countertop template", "c3", -1, "High", "To do"],
    ["p1", "Install LVP flooring", "c2", 2, "High", "In progress"],
    ["p1", "Complete electrical rough-in", "c4", -4, "Medium", "Done"],
    ["p1", "Remove existing cabinets", "c1", -12, "Medium", "Done"],
    ["p1", "Protect adjacent living areas", "c1", -16, "Medium", "Done"],
    ["p1", "Schedule final walkthrough", "c1", 18, "Low", "To do"],
    ["p2", "Approve shower tile layout", "c5", 0, "High", "To do"],
    ["p2", "Install double vanity", "c5", 4, "Medium", "To do"],
    ["p2", "Complete demolition", "c5", -10, "Medium", "Done"],
    ["p3", "Schedule framing inspection", "c1", -2, "High", "To do"],
    ["p3", "Run basement electrical", "c4", 5, "Medium", "In progress"],
    ["p4", "Confirm decking selection", "c1", 3, "Medium", "To do"],
    ["p5", "Follow up on material selections", "c2", 1, "Medium", "To do"],
    ["p6", "Complete final walkthrough", "c5", -4, "Medium", "Done"],
  ];
  const tasks = taskRows.map(
    ([projectId, title, contractorId, due, priority, status], i): Task => ({
      ...base,
      id: `t${i}`,
      projectId,
      title,
      contractorId,
      dueDate: day(due),
      priority,
      status,
      description: "",
    }),
  );
  const scope: ScopeItem[] = [
    {
      ...base,
      id: "s1",
      projectId: "p1",
      title: "Flooring · luxury vinyl plank",
      quantity: 1000,
      unit: "sq ft",
      estimate: 5000,
      subCost: 3000,
      contractorId: "c2",
      status: "In progress",
    },
    {
      ...base,
      id: "s2",
      projectId: "p1",
      title: "Quartz countertops",
      quantity: 40,
      unit: "sq ft",
      estimate: 8000,
      subCost: 6000,
      contractorId: "c3",
      status: "To do",
    },
    {
      ...base,
      id: "s3",
      projectId: "p1",
      title: "Electrical & lighting",
      quantity: 1,
      unit: "job",
      estimate: 3500,
      subCost: 2000,
      contractorId: "c4",
      status: "Done",
    },
    {
      ...base,
      id: "s4",
      projectId: "p1",
      title: "Cabinetry & installation",
      quantity: 1,
      unit: "job",
      estimate: 22000,
      subCost: 15200,
      contractorId: "c1",
      status: "In progress",
    },
    {
      ...base,
      id: "s5",
      projectId: "p1",
      title: "Tile backsplash & finish work",
      quantity: 1,
      unit: "job",
      estimate: 10000,
      subCost: 4800,
      contractorId: "c5",
      status: "To do",
    },
    {
      ...base,
      id: "s6",
      projectId: "p2",
      title: "Shower tile & waterproofing",
      quantity: 180,
      unit: "sq ft",
      estimate: 9500,
      subCost: 6500,
      contractorId: "c5",
      status: "In progress",
    },
  ];
  const contacts: Contact[] = [
    {
      ...base,
      id: "00000000-0000-4000-8000-000000000101",
      firstName: "Taylor",
      lastName: "Reed",
      name: "Taylor Reed",
      email: "taylor@example.com",
      phone: "+19195550142",
      zip: "27513",
      address: "1214 Willowbrook Drive, Cary, NC",
      source: "Premium Remodel website",
    },
  ];
  const leads: Lead[] = [
    {
      ...base,
      id: "00000000-0000-4000-8000-000000000102",
      contactId: contacts[0].id,
      name: contacts[0].name,
      project: "Kitchen Remodel",
      projectDescription:
        "We would like to update our cabinets, countertops, lighting, and flooring while keeping the current kitchen layout.",
      status: "New",
      source: "Premium Remodel website",
      submittedAt: new Date(Date.now() - 45 * 60_000).toISOString(),
      quoteDate: day(2),
      quoteStartTime: "14:00",
      quoteEndTime: "15:00",
      quoteNotes:
        "Homeowner asked for a kitchen walkthrough and cabinet options.",
    },
  ];
  const doorVisits: DoorVisit[] = [
    {
      ...base,
      id: "door-sample-1",
      address: contacts[0].address,
      latitude: 35.7826,
      longitude: -78.7817,
      visitedAt: new Date(Date.now() - 45 * 60_000).toISOString(),
      outcome: "Lead captured",
      notes: "Interested in a fall kitchen renovation.",
      canvasserId: "demo",
      canvasserName: "Alex Morgan",
      leadId: leads[0].id,
    },
    {
      ...base,
      id: "door-sample-2",
      address: "1208 Willowbrook Drive, Cary, NC 27513",
      latitude: 35.7822,
      longitude: -78.7809,
      visitedAt: new Date(Date.now() - 90 * 60_000).toISOString(),
      outcome: "Not home",
      notes: "Left a door hanger.",
      canvasserId: "demo",
      canvasserName: "Alex Morgan",
    },
    {
      ...base,
      id: "door-sample-3",
      address: "1220 Willowbrook Drive, Cary, NC 27513",
      latitude: 35.7831,
      longitude: -78.7822,
      visitedAt: new Date(Date.now() - 2 * 60 * 60_000).toISOString(),
      outcome: "Spoke — follow up",
      notes: "Call back after 5 PM about deck resurfacing.",
      canvasserId: "demo",
      canvasserName: "Alex Morgan",
    },
  ];
  return {
    projects,
    tasks,
    contractors,
    scope,
    attachments: [],
    activities: [],
    contacts,
    leads,
    doorVisits,
    comments: [
      {
        ...base,
        id: "n1",
        projectId: "p1",
        authorId: "demo",
        authorName: "Alex Morgan",
        body: "Cabinets are on site and ready for installation. Please keep the countertop template appointment on the calendar.",
        createdAt: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        ...base,
        id: "n2",
        projectId: "p2",
        authorId: "demo",
        authorName: "Alex Morgan",
        body: "The client approved the brushed nickel fixtures. Final tile layout still needs a sign-off.",
        createdAt: new Date(Date.now() - 7200000).toISOString(),
      },
    ],
  };
}
